image:
  file: .gitpod.Dockerfile

tasks:
  - name: init-conf-dirs
    init: ./scripts/init-conf-dirs.sh
    command: gp sync-done init-conf-dirs
    
  - name: init-dev-env
    command: ./scripts/init-dev-env.sh

  - name: minio-server
    command: ./scripts/start-minio-server.sh

  - name: livy-server
    command: |
      gp sync-await init-conf-dirs
      ./scripts/start-livy-server.sh
    
  - name: jupyter-server
    command: |
      gp sync-await init-conf-dirs
      ./scripts/start-jupyter-server.sh

  - name: spark-cluster
    command: |
      gp sync-await init-conf-dirs
      ./scripts/start-spark-cluster.sh

ports:
  - name: minio-s3
    description: MinIO S3
    port: 9000
    onOpen: ignore

  - name: minio-web
    description: MinIO Web
    port: 9090
    onOpen: ignore

  - name: livy
    description: Livy HTTP
    port: 8998
    onOpen: ignore

  - name: jupyter
    description: Jupyter server
    port: 8888
    onOpen: ignore

  - name: spark-master
    description: Spark Master
    port: 7077
    onOpen: ignore

  - name: spark-master-ui
    description: Spark Master UI
    port: 8080
    onOpen: ignore

  - name: mysql-server
    description: MySQL server
    port: 3306
    onOpen: ignore

    