image:
  file: .gitpod.Dockerfile

tasks:
  - name: init-conf-dirs
    init: ./scripts/init-conf-dirs.sh
    command: gp sync-done init-conf-dirs
    
  - name: init-spark-deps
    init: ./scripts/init-spark-deps.sh

  - name: minio-server
    command: ./scripts/start-minio-server.sh

  - name: livy-server
    command: |
      gp sync-await init-conf-dirs
      ./scripts/start-livy-server.sh
    
  - name: jupyter-server
    init: ./scripts/init-jupyter-server.sh
    command: |
      gp sync-await init-conf-dirs
      ./scripts/start-jupyter-server.sh

ports:
  - name: minio-s3
    description: MinIO S3
    port: 9000
    onOpen: ignore

  - name: minio-web
    description: MinIO Web
    port: 9090
    onOpen: ignore

  - name: livy
    description: Livy HTTP
    port: 8998
    onOpen: ignore

  - name: jupyter
    description: Jupyter notebok server
    port: 8888
    onOpen: ignore

    